### ISSUE TITLE
Add documentation for viewBox

### ISSUE THREAD

**Issue by crystalfp** [yeliulee/vue-mdi-svg#1]
Thanks for the library! I use it with great satisfaction under Vue3.
Could you add documentation for `:viewBox`? I discovered by trial and error that I have to use `:viewBox="'0,0,24,24'"` that is, a string.
Thanks!
mario

**Comment by yeliulee** [comment]
Thanks for reminding me, I will improve  the documentation as soon as possible.

**Comment by yeliulee** [comment]
resolved
